### ISSUE TITLE
Issue updating individual menu items and creating a checkout page

### ISSUE THREAD

**Issue by mlabita37** [mlabita37/Restaurantr#1]
So when I try to update a menu item, I'm getting an error that a "param is missing or the value is empty: order"  All the params are being called, and my delete method works without and issue. There shouldn't be any nil value either, so I'm really not sure what's happening. 

I'm also having difficulty wrapping my mind around setting up a checkout page. I just want to have a collectio_select where you choose the party_id, then when submitted, creates a table of all the orders associated with that party_id. Then I'll add all the item quantities and prices together to get the order total. I'll also calculate the suggested tip amounts, according to percent, once I get the total.

**Comment by ajhofferber** [comment]
Hey Mike, thanks for giving a clear explanation in your issue. Want to hop out to the lobby and spike on trying to fix it?

**Comment by mlabita37** [comment]
be right there
