### ISSUE TITLE
Trouble with the .each method

### ISSUE THREAD

**Issue by mlabita37** [mlabita37/Restaurantr#3]
I'm not executing my .each method correctly . I'm using it to create a new table, but instead of creating multiple rows, it's trying to put the data into one row. I normally just use the "do" method with an iterator, but that's not working either.

**Comment by mlabita37** [comment]
Nevermind... I literally thought of what the problem could be right after submitting. I didn't have my <tr> tags included in the .each method, hence only one row. Solved!

**Comment by ajhofferber** [comment]
NICE!
